### ISSUE TITLE
Errors parsing theme

### ISSUE THREAD

**Issue by YoSTEALTH** [kaste/PyTest#33]
Hi,

So this is happening all of a sudden, and its messing up all the icons throughout sublimetext

``` Python
Run /opt/python/3.10/bin/python3 -m pytest -sv test
Errors parsing theme:
  "class" is required in Packages/User/Adaptive.sublime-theme:66:2
Errors parsing theme:
  "class" is required in Packages/User/Adaptive.sublime-theme:66:2
glGetError: GL_INVALID_OPERATION
Run /opt/python/3.10/bin/python3 -m pytest -sv test
Errors parsing theme:
  "class" is required in Packages/User/Adaptive.sublime-theme:66:2
Errors parsing theme:
  "class" is required in Packages/User/Adaptive.sublime-theme:66:2
Errors parsing theme:
  "class" is required in Packages/User/Adaptive.sublime-theme:66:2
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
font face "Times" could not be found, defaulting to "Monospace"
```
File: `Adaptive.sublime-theme`
``` Python

[
	{
		"class": "status_bar",
		"layer0.tint":
		[
			8,
			131,
			8
		],
		"settings":
		[
			"pytest_is_green"
		]
	},
	{
		"class": "label_control",
		"color":
		[
			19,
			21,
			32
		],
		"parents":
		[
			{
				"class": "status_bar"
			}
		],
		"settings":
		[
			"pytest_is_green"
		]
	},
	{
		"class": "status_bar",
		"layer0.tint":
		[
			155,
			7,
			8
		],
		"settings":
		[
			"pytest_is_red"
		]
	},
	{
		"class": "label_control",
		"color":
		[
			199,
			191,
			192
		],
		"parents":
		[
			{
				"class": "status_bar"
			}
		],
		"settings":
		[
			"pytest_is_red"
		]
	},
]

```

**Comment by kaste** [comment]
Sorry, don't get it.  You don't even tell what's happening.  `glGetError: GL_INVALID_OPERATION` is probably a problem.  

Other than that, the posted `Adaptive` file does not have anything on pos `66:2`. Do you actually see anything not having a `class` key?

**Comment by YoSTEALTH** [comment]
To be perfectly honest with you, I am not really sure whats going on, as I have only used sublime, not created any package for it. I only saw the error log and posted it here, figure maybe you would know whats going on!

If its actually a `glGetError: GL_INVALID_OPERATION` thing, we will have to wait for sublime to fix this in their next  update.

**Comment by kaste** [comment]
Yeah, I don't know the testing strategy here.  If you think the `Adaptive` file you posted here is the problem, just delete everything from it, leaving just an empty `[]`.  As I can see these are only 4 rules anyway, so you can remove them and then re-add one by one.  

You still don't say what `messing up all the icons` looks like.

**Comment by YoSTEALTH** [comment]
Its a random error, I am not really sure how to recreate it! I will just have to wait till it happens again. Maybe its a sublimetext error and nothing to do with PyTest! I dono, figure maybe you would like to know.

Pretty much all the icons go missing or change to wrong icons.
