### ISSUE TITLE
keybinding conflict

### ISSUE THREAD

**Issue by lampda** [kaste/PyTest#39]
I am using ST4 on my MBP, and installed pytest yesterday.

I found there is a conflict or unwanted behaviour. That the "cmd+s" will run pytest runner is not acceptable, since by default "cmd+s" is to save changes in files.

I would like to see there is another keybinding to trigger pytest runner, other than "cmd+s".

**Comment by kaste** [comment]
Totally, but there is setting for that:

https://github.com/kaste/PyTest/blob/master/PyTest.sublime-settings#L21-L23

You want "manual" and then you can bind any key you want (or use the Command Palette `ctrl+shift+p`).

E.g.

```
	{ "keys": ["ctrl+..."], "command": "pytest_auto_run" },
```

**Comment by lampda** [comment]
conflict resolved, thank you.
