### ISSUE TITLE
Add a command to hide inline errors annotations from views

### ISSUE THREAD

**Issue by bofm** [kaste/PyTest#5]
It would be great to have a shortcut to toggle inline annotations in views.

**Comment by kaste** [comment]
That's a really good idea. We still should flash the status bar green/red, and keep drawing the regions, just remove what sublime calls `phantoms`, right?

**Comment by bofm** [comment]
Here is how I think of it. The command should toggle the phantoms display in Sublime view. A subsequent test run should show the phantoms back or keep them hidden depending on some parameter in the config.

**Comment by kaste** [comment]
That's exactly how we should do this.

**Comment by kaste** [comment]
Take a look at my PR. Can you test this?

**Comment by bofm** [comment]
Will test it next week.

**Comment by bofm** [comment]
Tested the PR on my Mac. It worked well. Thank you.

**Comment by kaste** [comment]
Merged and released as version `0.7.0`
