### ISSUE TITLE
cannot find settings file + python version mismatch

### ISSUE THREAD

**Issue by roberto-arista** [kaste/PyTest#9]
Hi!
I know it's a stupid question, but I cannot find the plugin settings file into my sublime text application support folder
~/Library/Application Support/Sublime Text 3/Packages

Am I supposed to create it myself? Is it stored somewhere else?
It would be maybe good idea to mention its position into the README

btw, my issue is that the standard python used for my builds in ST3 is brew python3 located
/usr/local/bin/python3

instead pytest is executed from python2.

How can I match them?

**Comment by kaste** [comment]
You edit the settings via Menu `Preferences > Package Settings > PyTest Runner`. It will create a new settings file on the first run.

Using the settings, you can point to the correct pytest binary.

**Comment by roberto-arista** [comment]
thank you!
